platform :ios, '17.0.1'

target 'NewsLetterFeedApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'SDWebImageSwiftUI'
  
  use_frameworks!

  # Pods for NewsLetterFeedApp

end
